remote_theme: pages-themes/merlot@v0.2.0
title: Moore Discord Bot
description: Language Learner Bot is an open source Discord bot built to help users learn languages like French 🇫🇷, Spanish 🇪🇸, Hindi 🇮🇳, Japanese 🇯🇵, Korean 🇰🇷 etc. It was created for the NTTS Hackathon 2024.
